name: Trigger auto deployment for workshop-app-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/workshop-app-container-AutoDeployTrigger-b2fd3562-e4a4-49a9-a236-1f07f7c1c244.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WORKSHOPAPPCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WORKSHOPAPPCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WORKSHOPAPPCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.WORKSHOPAPPCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WORKSHOPAPPCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: workshop-app-container
          resourceGroup: workshop-rg
          imageToBuild: noriegadocker/workshop-app-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


